# Generated by Django 6.0 on 2025-12-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
