# Generated by Django 6.0 on 2025-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='file_link',
        ),
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(default=1, upload_to='papers/'),
            preserve_default=False,
        ),
    ]
