# Generated by Django 6.0 on 2025-12-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_paper_file_link_paper_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
